version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    networks:
      - blog-network

  gateway:
    build:
      context: ./backend/gateway   
      dockerfile: Dockerfile
    container_name: sivaprasadpv/gateway
    ports:
      - "6000:6000"
    depends_on:
      - rabbitmq
      - user-service
      - blog-service
      - comment-service
    networks:
      - blog-network

  user-service:
    build:
      context: ./backend/services/user-service  
      dockerfile: Dockerfile
    container_name: sivaprasadpv/user-service
    ports:
      - "6500:6500"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

  comment-service:
    build:
      context: ./backend/services/comment-service 
      dockerfile: Dockerfile  
    container_name: sivaprasadpv/comment-service
    ports:
      - "6700:6700"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

  blog-service:
    build:
      context: ./backend/services/blog-service   
      dockerfile: Dockerfile
    container_name: sivaprasadpv/blog-service
    ports:
      - "6600:6600"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
