version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ port
      - "15672:15672"  # RabbitMQ Management UI port
    networks:
      - blog-network

  gateway:
    build:
      context: ./backend/gateway   # Path to your gateway service
    ports:
      - "6000:6000"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

  user-service:
    build:
      context: ./backend/service/user-service   # Path to your user service
    ports:
      - "6500:6500"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

  comment-service:
    build:
      context: ./backend/service/comment-service   # Path to your comment service
    ports:
      - "6700:6700"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

  blog-service:
    build:
      context: ./backend/service/blog-service   # Path to your blog service
    ports:
      - "6600:6600"
    depends_on:
      - rabbitmq
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
