# This is the CI/CD pipeline for the blog microservices project
name: CI/CD for Microservices Blog Project

on:
  push:
    branches: [ master ]  # This will trigger the workflow for push events on the master branch
  pull_request:
    branches: [ master ]  # This will trigger the workflow for pull request events on the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Use Node.js version 20.x

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Install Dependencies and Build Each Service
      run: |
        cd backend/services/user-service
        npm ci
        npm run build
        cd ../blog-service
        npm ci
        npm run build
        cd ../comment-service
        npm ci
        npm run build
        cd ../../gateway
        npm ci
        npm run build

    - name: Build & Push User Service
      run: |
        docker build -t sivaprasadpv/blog-user:latest ./backend/services/user-service
        docker push sivaprasadpv/blog-user:latest

    - name: Build & Push Blog Service
      run: |
        docker build -t sivaprasadpv/blog-service:latest ./backend/services/blog-service
        docker push sivaprasadpv/blog-service:latest

    - name: Build & Push Comment Service
      run: |
        docker build -t sivaprasadpv/comment-service:latest ./backend/services/comment-service
        docker push sivaprasadpv/comment-service:latest

    - name: Build & Push API Gateway
      run: |
        docker build -t sivaprasadpv/blog-gateway:latest ./backend/gateway
        docker push sivaprasadpv/blog-gateway:latest

# You can uncomment this if you want to automatically deploy using docker-compose
#    - name: Deploy to Docker Compose
#      run: |
#        docker-compose -f docker-compose.yml up -d
